### ISSUE TITLE
Powerups not fully implemented

### ISSUE THREAD

**Issue by Jester565** [Jester565/SpyNinjaGame#24] opened 2016-11-20 10:37 UTC
@kjasonk 
While the player has invincibility they can still die.  To fix this, you need to overload the takeDamage method in Spy.  Make sure that they cannot take damage when isInvincible() is true.  [Example](https://github.com/Jester565/SpyNinjaGame/blob/DevAhead/SpyGame/src/edu/cpp/cs/cs141/final_proj/Spy.java#L122-L132).  However, GameEngine is not supporting this implementation, I will fix it.

I'll add another comment in a second.

**Comment by Jester565** [comment] 2016-11-20 10:43
@kjasonk 
A very important method in implementing radar is the [Room::revealBriefCase() method](https://github.com/Jester565/SpyNinjaGame/blob/671306de822036081febb109a6bfc55a05dae385/SpyGame/src/edu/cpp/cs/cs141/final_proj/Room.java#L86-L89).  You should call this method when the Spy gets his radar.  To do this take a look at the [GameEngine::updateSpyPowerups() method](https://github.com/Jester565/SpyNinjaGame/blob/DevAhead/SpyGame/src/edu/cpp/cs/cs141/final_proj/GameEngine.java#L227-L234).

**Comment by Jester565** [comment] 2016-11-20 10:50
@kjasonk 
The bullet powerup should not be consumed unless the ammo is actually picked up.  Therefore, you are going to have to change the [Useable interface](https://github.com/Jester565/SpyNinjaGame/blob/DevAhead/SpyGame/src/edu/cpp/cs/cs141/final_proj/Useable.java#L12) to return a boolean.  When the boolean is true, that means that the powerup should be consumed.  When it is false that means don't consume.  This has to be handled in the [Spy::usePowerups() method](https://github.com/Jester565/SpyNinjaGame/blob/DevAhead/SpyGame/src/edu/cpp/cs/cs141/final_proj/Spy.java#L67-L76).

**Comment by jtara1** [comment] 2016-11-21 00:32
I tested this out a few times. It seems to work as expected (mostly).

With Jason's commit bfbf8fe6480d725bcecca5ca6d40b263cee447d8 all consumables work almost perfectly.

What's expected when one of the `Useable` is acquired:
* [x] Bullet stays in game when spy has max ammo or is removed and applied when spy has less than max ammo
* [x] Radar immediately reveals the room with the briefcase
* [x] Invincibility needs to show there's 5 turns of invincibility & enable the spy to not die

---

**Changes / fixes needed:**

* As we can see from the game prints, the invincibility works as intended, but it states there's **4** turns of the invinc. and not the expected **5**.
* There's a typo, people keep confusing the words *invincibility* and *invisibility*
```
[ ][B][ ][ ][ ][ ][ ][ ][ ]   Lives: 3
[ ][b][ ][N][R][ ][N][R][ ]   Ammo: 1
[ ][ ][ ][ ][ ][ ][ ][ ][ ]   Invincible Turns: 0
[ ][ ][N][ ][ ][ ][ ][ ][ ]   Radar: Disabled
[ ][R][ ][ ][R][N][ ][R][ ]
[ ][ ][ ][ ][ ][ ][ ][ ][N]
[ ][ ][ ][ ][ ][ ][N][ ][ ]
[ ][R][ ][ ][R][ ][I][R][ ]
[ ][ ][ ][ ][ ][ ][S][ ][r]

Enter a direction to move or another command
W: Up | A: Left | S: Down | D: Right
1: Shoot | 2: Debug | 3: More Options
w
Move Status: You aquired invisiblility!
[ ][B][ ][N][ ][ ][ ][ ][ ]   Lives: 3
[ ][b][ ][ ][R][N][ ][R][ ]   Ammo: 1
[ ][ ][ ][ ][ ][ ][ ][ ][ ]   Invincible Turns: 4
[ ][ ][ ][ ][ ][ ][ ][ ][ ]   Radar: Disabled
[ ][R][N][ ][R][ ][N][R][N]
[ ][ ][ ][ ][ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ][N][ ][ ][ ]
[ ][R][ ][ ][R][ ][S][R][ ]
[ ][ ][ ][ ][ ][ ][ ][ ][r]

Enter a direction to look in or another command
W: Up | A: Left | S: Down | D: Right
2: Debug | 3: More Options
w
[ ][B][ ][N][ ][ ][ ][ ][ ]   Lives: 3
[ ][b][ ][ ][R][N][ ][R][ ]   Ammo: 1
[ ][ ][ ][ ][ ][ ][ ][ ][ ]   Invincible Turns: 4
[ ][ ][ ][ ][ ][ ][ ][ ][ ]   Radar: Disabled
[ ][R][N][ ][R][ ][N][R][N]
[ ][ ][ ][ ][ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ][N][ ][ ][ ]
[ ][R][ ][ ][R][ ][S][R][ ]
[ ][ ][ ][ ][ ][ ][ ][ ][r]

Enter a direction to move or another command
W: Up | A: Left | S: Down | D: Right
1: Shoot | 2: Debug | 3: More Options
w
Move Status: Moved!
[ ][B][ ][ ][ ][ ][ ][ ][ ]   Lives: 3
[ ][b][ ][N][R][ ][N][R][ ]   Ammo: 1
[ ][ ][ ][ ][ ][ ][ ][ ][ ]   Invincible Turns: 3
[ ][ ][ ][ ][ ][ ][N][ ][N]   Radar: Disabled
[ ][R][ ][ ][R][ ][ ][R][ ]
[ ][ ][N][ ][ ][ ][ ][ ][ ]
[ ][ ][ ][ ][ ][ ][S][ ][ ]
[ ][R][ ][ ][R][N][ ][R][ ]
[ ][ ][ ][ ][ ][ ][ ][ ][r]

Enter a direction to look in or another command
W: Up | A: Left | S: Down | D: Right
2: Debug | 3: More Options

```

**Comment by jtara1** [comment] 2016-11-21 03:30
Closing with commit af00bfb5052730c2c1f70f7be2f4035366f8a195

**Closed as completed by jtara1** 2016-11-21 03:30 UTC
Labels: bug
